services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    user: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: xyz
        POSTGRES_USER: alice
        POSTGRES_DB: menu
        PGPASSWORD: xyz
    command: ["postgres"]