[tool.poetry]
name = "e-menu"
version = "0.1.0"
description = ""
authors = ["Kacper Misiek <315560@uwr.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
